// Director Action Types
export const FETCH_DIRECTORS = 'FETCH_DIRECTORS'
export const FETCH_DIRECTOR = 'FETCH_DIRECTOR'
export const CREATE_DIRECTOR = 'CREATE_DIRECTOR'
export const EDIT_DIRECTOR = 'EDIT_DIRECTOR'
export const DELETE_DIRECTOR = 'DELETE_DIRECTOR'